"""empty message

Revision ID: 059d75d70fe8
Revises: 8d0917dbe165
Create Date: 2025-05-16 17:59:13.937485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059d75d70fe8'
down_revision = '8d0917dbe165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('users_gender_id_fkey', type_='foreignkey')
        batch_op.drop_column('last_name')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('gender_id')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_gender_id_fkey', 'genders', ['gender_id'], ['id'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###
