"""empty message

Revision ID: 10aa48589b67
Revises: 2f7977f44750
Create Date: 2025-06-02 20:40:32.641723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aa48589b67'
down_revision = '2f7977f44750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_books', schema=None) as batch_op:
        batch_op.drop_constraint('explore_books_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], referent_schema='public')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_explore_book_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_personal_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personal_books', ['personal_book_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'explore_books', ['explore_book_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('personal_books', schema=None) as batch_op:
        batch_op.drop_constraint('personal_books_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], referent_schema='public')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('reviews_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reviews_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'personal_books', ['book_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_book_id_fkey', 'personal_books', ['book_id'], ['id'])
        batch_op.create_foreign_key('reviews_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('book_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('personal_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('personal_books_created_by_fkey', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_personal_book_id_fkey', 'personal_books', ['personal_book_id'], ['id'])
        batch_op.create_foreign_key('favorites_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorites_explore_book_id_fkey', 'explore_books', ['explore_book_id'], ['id'])

    with op.batch_alter_table('explore_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('explore_books_created_by_fkey', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
