"""empty message

Revision ID: b9777e660df0
Revises: 059d75d70fe8
Create Date: 2025-05-16 18:01:48.457683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9777e660df0'
down_revision = '059d75d70fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('gender_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'genders', ['gender_id'], ['id'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gender_id')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
