"""empty message

Revision ID: fa9d2fe4a233
Revises: 9e3dd2320c8e
Create Date: 2025-06-02 02:19:03.444748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9d2fe4a233'
down_revision = '9e3dd2320c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explore_books', schema=None) as batch_op:
        batch_op.drop_constraint('explore_books_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], referent_schema='public')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_explore_book_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_personal_book_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'explore_books', ['explore_book_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'personal_books', ['personal_book_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('personal_books', schema=None) as batch_op:
        batch_op.drop_constraint('personal_books_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'], referent_schema='public')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_book_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reviews_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personal_books', ['book_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rol')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('reviews_book_id_fkey', 'personal_books', ['book_id'], ['id'])

    with op.batch_alter_table('personal_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('personal_books_created_by_fkey', 'users', ['created_by'], ['id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorites_personal_book_id_fkey', 'personal_books', ['personal_book_id'], ['id'])
        batch_op.create_foreign_key('favorites_explore_book_id_fkey', 'explore_books', ['explore_book_id'], ['id'])

    with op.batch_alter_table('explore_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('explore_books_created_by_fkey', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###
